name: Java CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [8, 9, 11]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug before
        run: echo "Before mvn install"

      - name: Install spring-boot-starter-parent
        run: |
          mvn install:install-file \
            -Dfile=spring-boot-starter-parent-2.7.15.pom \
            -DgroupId=org.springframework.boot \
            -DartifactId=spring-boot-starter-parent \
            -Dversion=2.7.15 \
            -Dpackaging=pom

      - name: Install maven-shared-utils
        run: |
          mvn install:install-file \
            -Dfile=maven-shared-utils-3.3.4.pom \
            -DgroupId=org.apache.maven.shared \
            -DartifactId=maven-shared-utils \
            -Dversion=3.3.4 \
            -Dpackaging=pom

      - name: Install maven-shared-components
        run: |
          mvn install:install-file \
            -Dfile=maven-shared-components-34.pom \
            -DgroupId=org.apache.maven.shared \
            -DartifactId=maven-shared-components \
            -Dversion=34 \
            -Dpackaging=pom

      - name: Debug after
        run: echo "After mvn install"

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Build with Maven
        run: mvn clean install

      - name: Test and report coverage
        run: mvn clean test jacoco:report coveralls:report
